from django.urls import path

from .views import (
    AdminCategoryDetailView,
    AdminCategoryListCreateView,
    AdminCustomerListView,
    AdminDetailView,
    AdminListCreateView,
    AdminProductDetailView,
    AdminProductListCreateView,
    AdminSettingsView,
    BannerDetailView,
    BannerListCreateView,
    BestSellerProductListView,
    CategoryDetailView,
    CategoryListView,
    CategorySlugDetailView,
    DashboardRecentOrdersView,
    DashboardStatsView,
    FeaturedProductListView,
    HealthCheckView,
    LoginView,
    OrderByUserListView,
    OrderDetailView,
    OrderListView,
    OrderStatusUpdateView,
    ProductDetailView,
    ProductListView,
    ProductSlugDetailView,
    PublicSettingsView,
    QuoteRequestCreateView,
    QuoteRequestListView,
    QuoteRequestStatusUpdateView,
    RegisterView,
    RelatedProductListView,
    TestimonialDetailView,
    TestimonialListCreateView,
)

urlpatterns = [
    path("health/", HealthCheckView.as_view()),
    path("auth/login/", LoginView.as_view()),
    path("auth/register/", RegisterView.as_view()),
    path("store/categories/", CategoryListView.as_view()),
    path("store/categories/<int:pk>/", CategoryDetailView.as_view()),
    path("store/categories/slug/<slug:slug>/", CategorySlugDetailView.as_view()),
    path("store/products/", ProductListView.as_view()),
    path("store/products/featured/", FeaturedProductListView.as_view()),
    path("store/products/best-sellers/", BestSellerProductListView.as_view()),
    path("store/products/<int:pk>/", ProductDetailView.as_view()),
    path("store/products/slug/<slug:slug>/", ProductSlugDetailView.as_view()),
    path("store/products/<int:pk>/related/", RelatedProductListView.as_view()),
    path("store/orders/", OrderListView.as_view()),
    path("store/orders/<int:pk>/", OrderDetailView.as_view()),
    path("store/orders/by-user/", OrderByUserListView.as_view()),
    path("store/quotes/", QuoteRequestCreateView.as_view()),
    path("store/banners/", BannerListCreateView.as_view()),
    path("store/testimonials/", TestimonialListCreateView.as_view()),
    path("store/settings/", PublicSettingsView.as_view()),
    path("admin/dashboard/stats/", DashboardStatsView.as_view()),
    path("admin/dashboard/recent-orders/", DashboardRecentOrdersView.as_view()),
    path("admin/products/", AdminProductListCreateView.as_view()),
    path("admin/products/<int:pk>/", AdminProductDetailView.as_view()),
    path("admin/categories/", AdminCategoryListCreateView.as_view()),
    path("admin/categories/<int:pk>/", AdminCategoryDetailView.as_view()),
    path("admin/orders/", OrderListView.as_view()),
    path("admin/orders/<int:pk>/status/", OrderStatusUpdateView.as_view()),
    path("admin/quotes/", QuoteRequestListView.as_view()),
    path("admin/quotes/<int:pk>/status/", QuoteRequestStatusUpdateView.as_view()),
    path("admin/customers/", AdminCustomerListView.as_view()),
    path("admin/admins/", AdminListCreateView.as_view()),
    path("admin/admins/<int:pk>/", AdminDetailView.as_view()),
    path("admin/content/banners/", BannerListCreateView.as_view()),
    path("admin/content/banners/<int:pk>/", BannerDetailView.as_view()),
    path("admin/content/testimonials/", TestimonialListCreateView.as_view()),
    path("admin/content/testimonials/<int:pk>/", TestimonialDetailView.as_view()),
    path("admin/settings/", AdminSettingsView.as_view()),
]
