# Generated by Django 6.0.6 on 2026-06-22 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('quotes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quote_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='quotes.quoterequest'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['quote_request', 'status'], name='orders_orde_quote_r_bd30ab_idx'),
        ),
    ]
