# Generated by Django 6.0.6 on 2026-08-11 06:59

from django.conf import settings
from django.db import migrations, models


def classify_quote_orders(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(quote_request_id__isnull=False).update(source="quote")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_stock_deducted'),
        ('quotes', '0004_quoterequest_admin_message_quoterequest_quoted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct checkout'), ('quote', 'Accepted quote'), ('admin', 'Admin created')], db_index=True, default='admin', max_length=20),
        ),
        migrations.RunPython(classify_quote_orders, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['source', 'status'], name='orders_orde_source_e9e197_idx'),
        ),
    ]
