# Generated by Django 6.0.6 on 2026-08-24

import django.db.models.deletion
from django.db import migrations, models


def associate_unambiguous_legacy_orders(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Membership = apps.get_model("licensing", "OrganizationMembership")

    for order in Order.objects.filter(organization__isnull=True, user__isnull=False).iterator():
        organization_ids = list(
            Membership.objects.filter(
                user_id=order.user_id,
                is_active=True,
                organization__is_active=True,
            ).values_list("organization_id", flat=True)[:2]
        )
        if len(organization_ids) == 1:
            order.organization_id = organization_ids[0]
            order.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0004_alter_licenseevent_event_type"),
        ("orders", "0007_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="licensing.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["organization", "status"], name="orders_orde_organiz_b4ac87_idx"),
        ),
        migrations.RunPython(associate_unambiguous_legacy_orders, migrations.RunPython.noop),
    ]
