# Generated by Django 6.0.6 on 2026-08-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("licensing", "0004_alter_licenseevent_event_type"),
        ("orders", "0008_order_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="renewal_license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewal_orders",
                to="licensing.license",
            ),
        ),
    ]
