# Generated by Django 6.0.8 on 2026-08-26 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_draft_and_created_by'),
        ('products', '0007_product_license_capacity_product_license_term_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('consumed', 'Consumed'), ('released', 'Released')], db_index=True, default='reserved', max_length=20)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=255)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservation', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='products.product')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['product', 'status'], name='orders_inve_product_494fb4_idx'), models.Index(fields=['status', 'created_at'], name='orders_inve_status_ee23a4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orders_inventory_reservation_positive_quantity')],
            },
        ),
    ]
