# Generated by Django 6.0.8 on 2026-08-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_inventory_reservation'),
        ('products', '0007_product_license_capacity_product_license_term_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='backordered_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('ready', 'Ready to ship'), ('partially_ready', 'Partially ready'), ('backordered', 'Awaiting stock'), ('fulfilled', 'Fulfilled')], db_index=True, default='not_required', max_length=24),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('backordered', 'Awaiting stock'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['fulfillment_status'], name='orders_orde_fulfill_1ba673_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='orders_item_reserved_quantity_not_over_ordered'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('backordered_quantity__lte', models.F('quantity'))), name='orders_item_backordered_quantity_not_over_ordered'),
        ),
    ]
