# Generated by Django 6.0.8 on 2026-09-03 03:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_backordered_quantity_and_more'),
        ('products', '0008_inventoryadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('shipped_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('shipping_address', models.CharField(max_length=255)),
                ('shipping_city', models.CharField(max_length=120)),
                ('shipping_state', models.CharField(blank=True, max_length=120)),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20)),
                ('shipping_country', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='inventoryreservation',
            name='orders_inventory_reservation_positive_quantity',
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='orders_inventory_reservation_positive_quantity'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.shipment'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order', 'shipped_at'], name='orders_ship_order_i_1b6cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['shipment', 'order_item'], name='orders_ship_shipmen_125d16_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['order_item', 'shipment'], name='orders_ship_order_i_573d0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orders_shipment_item_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.UniqueConstraint(fields=('shipment', 'order_item'), name='orders_shipment_item_unique_shipment_order_item'),
        ),
    ]
