web: DJANGO_SETTINGS_MODULE=config.settings.prod gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 60
worker: DJANGO_SETTINGS_MODULE=config.settings.prod python manage.py process_notifications
