import { useState, type ReactNode } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, CheckCircle2, Copy, Crown, LoaderCircle, RefreshCw, ShieldCheck, UserPlus, XCircle } from 'lucide-react'
import { ApiError, api } from '../../../lib/api'
import { licensingKeys } from '../queryKeys'

export function OrganizationTeamPanel({ organizationId }: { organizationId: number | null }) {
  const queryClient = useQueryClient()
  const [inviteOpen, setInviteOpen] = useState(false)
  const [email, setEmail] = useState('')
  const [feedback, setFeedback] = useState<{ tone: 'success' | 'error' | 'info'; message: string } | null>(null)
  const [invitationLink, setInvitationLink] = useState<string | null>(null)
  const teamQuery = useQuery({ queryKey: licensingKeys.team(organizationId), queryFn: () => api.organizationTeam(organizationId), enabled: organizationId !== null })
  const refreshTeam = () => queryClient.invalidateQueries({ queryKey: licensingKeys.team(organizationId) })
  const inviteMutation = useMutation({ mutationFn: (inviteEmail: string) => api.inviteLicenseManager(inviteEmail, organizationId), onSuccess: async (invitation) => { setInviteOpen(false); setEmail(''); setInvitationLink(invitation.accept_url ?? null); setFeedback({ tone: 'success', message: `Invitation sent to ${invitation.email}.` }); await refreshTeam() }, onError: (error) => setFeedback({ tone: 'error', message: messageFrom(error) }) })
  const resendMutation = useMutation({ mutationFn: (invitationId: number) => api.resendOrganizationInvitation({ invitationId, organizationId }), onSuccess: async (invitation) => { setInvitationLink(invitation.accept_url ?? null); setFeedback({ tone: 'success', message: `A new invitation was sent to ${invitation.email}. The previous link no longer works.` }); await refreshTeam() }, onError: (error) => setFeedback({ tone: 'error', message: messageFrom(error) }) })
  const revokeMutation = useMutation({ mutationFn: (invitationId: number) => api.revokeOrganizationInvitation({ invitationId, organizationId }), onSuccess: async (invitation) => { setFeedback({ tone: 'success', message: `Invitation for ${invitation.email} was revoked.` }); await refreshTeam() }, onError: (error) => setFeedback({ tone: 'error', message: messageFrom(error) }) })
  const transferMutation = useMutation({ mutationFn: (membershipId: number) => api.transferOrganizationOwnership({ membershipId, organizationId }), onSuccess: async () => { setFeedback({ tone: 'success', message: 'Organization ownership was transferred. You are now a License Manager.' }); await refreshTeam() }, onError: (error) => setFeedback({ tone: 'error', message: messageFrom(error) }) })
  const people = teamQuery.data
    ? [
        ...(teamQuery.data.owner ? [{ ...teamQuery.data.owner, rowId: `owner-${teamQuery.data.owner.id}`, kind: 'owner' as const, role: 'Organization Owner', status: 'Active' }] : []),
        ...teamQuery.data.license_managers.map((manager) => ({ ...manager, rowId: `manager-${manager.membership_id}`, kind: 'manager' as const, role: 'License Manager', status: 'Active' })),
        ...teamQuery.data.pending_invitations.map((invitation) => ({ rowId: `invitation-${invitation.invitation_id}`, invitationId: invitation.invitation_id, kind: 'invitation' as const, name: invitation.email, email: invitation.email, role: 'License Manager', status: 'Invitation pending' })),
      ]
    : []

  const canInvite = Boolean(teamQuery.data?.permissions.can_invite)
  const canRevoke = Boolean(teamQuery.data?.permissions.can_revoke_manager)
  const canTransfer = Boolean(teamQuery.data?.permissions.can_transfer_ownership)
  const permissionDenied = teamQuery.error instanceof ApiError && teamQuery.error.status === 403

  return <div className="grid gap-4">
    <header className="flex flex-wrap items-start justify-between gap-4 max-[560px]:gap-3"><div><h2 className="text-[28px] leading-tight">Organization team</h2><p className="mt-1 text-sm text-muted">{teamQuery.data?.organization.name ?? 'Your organization'} · Owners and License Managers</p></div><button className="inline-flex min-h-11 items-center gap-2 rounded-control border-0 bg-brand px-4 text-sm font-bold text-white disabled:opacity-55 max-[560px]:w-full max-[560px]:justify-center" type="button" disabled={!canInvite} title={canInvite ? undefined : 'Only the Organization Owner can invite License Managers.'} onClick={() => { setFeedback(null); setInviteOpen(true) }}><UserPlus size={19} />Invite License Manager</button></header>
    {teamQuery.isLoading ? <TeamState icon={<LoaderCircle className="animate-spin text-brand" size={22} />} title="Loading organization team" text="Retrieving the Organization Owner and License Managers." /> : null}
    {permissionDenied ? <TeamState icon={<ShieldCheck className="text-warning" size={22} />} title="Organization team access is required" text="Only the Organization Owner and invited License Managers can open this page." /> : null}
    {teamQuery.isError && !permissionDenied ? <TeamState icon={<AlertTriangle className="text-danger" size={22} />} title="Organization team could not be loaded" text={messageFrom(teamQuery.error)} action={<button className="inline-flex min-h-9 items-center gap-2 rounded-control border border-border-input bg-white px-3 text-xs font-bold text-brand" type="button" onClick={() => void teamQuery.refetch()}><RefreshCw size={15} />Try again</button>} /> : null}
    {!teamQuery.isLoading && !teamQuery.isError ? <>
    {feedback ? <p className={`flex items-start gap-2 rounded-control px-3 py-2.5 text-sm ${feedback.tone === 'success' ? 'bg-success-soft text-success' : feedback.tone === 'error' ? 'bg-danger-soft text-danger' : 'bg-info-soft text-brand'}`}>{feedback.tone === 'success' ? <CheckCircle2 className="mt-0.5 shrink-0" size={18} /> : feedback.tone === 'error' ? <XCircle className="mt-0.5 shrink-0" size={18} /> : <ShieldCheck className="mt-0.5 shrink-0" size={18} />}{feedback.message}</p> : null}
    {invitationLink ? <section className="rounded-panel border border-brand/30 bg-brand-soft p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-base">Invitation link ready</h3><p className="mt-1 text-sm text-muted">Copy this current link for local testing. Sending or resending another invitation will invalidate it.</p></div><button className="inline-flex min-h-10 items-center gap-2 rounded-control border border-brand bg-white px-3 text-sm font-bold text-brand" type="button" onClick={() => void navigator.clipboard.writeText(invitationLink)}><Copy size={16} />Copy link</button></div><p className="mt-3 break-all rounded-control border border-border bg-white px-3 py-2 text-xs text-muted">{invitationLink}</p></section> : null}
    {!canInvite && teamQuery.data ? <p className="flex items-start gap-2 rounded-control bg-info-soft px-3 py-2.5 text-sm text-brand"><ShieldCheck className="mt-0.5 shrink-0" size={18} />You can view organization licenses, but only the Organization Owner can invite, revoke, or transfer team control.</p> : null}
    {inviteOpen ? <form className="grid gap-3 rounded-panel border border-border bg-white p-5 max-[560px]:p-4" onSubmit={(event) => { event.preventDefault(); if (email.trim()) inviteMutation.mutate(email.trim()) }}><div><h3 className="text-lg">Invite License Manager</h3><p className="mt-1 text-sm text-muted">They can view licenses, capacity and renewal information for this organization.</p></div><label className="grid gap-1.5 text-sm font-bold">Email address<input className="min-h-11 min-w-0 rounded-control border border-border-input px-3 font-normal outline-none focus:border-brand" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="manager@company.com" required autoFocus /></label><div className="flex flex-wrap gap-2 max-[420px]:grid max-[420px]:grid-cols-2"><button className="min-h-10 rounded-control border-0 bg-brand px-4 text-sm font-bold text-white disabled:opacity-55" type="submit" disabled={inviteMutation.isPending}>{inviteMutation.isPending ? 'Sending invitation...' : 'Send invitation'}</button><button className="min-h-10 rounded-control border border-border-input bg-white px-4 text-sm font-bold" type="button" disabled={inviteMutation.isPending} onClick={() => { setInviteOpen(false); setEmail('') }}>Cancel</button></div></form> : null}
    {teamQuery.data?.owner ? <section className="rounded-panel border border-border bg-white p-5 max-[560px]:p-4"><div className="grid items-center gap-4 md:grid-cols-[minmax(0,1fr)_auto]"><Person name={teamQuery.data.owner.name} email={teamQuery.data.owner.email} /><span className="w-fit rounded-full bg-brand-soft px-3 py-1.5 text-xs font-bold text-brand max-[560px]:w-full max-[560px]:text-center">Billing and team control</span></div></section> : null}
    <section className="rounded-panel border border-border bg-white p-5 max-[560px]:p-4">
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3 max-[420px]:items-start max-[420px]:flex-col"><h3 className="text-xl">License Managers</h3><span className="text-sm text-muted">{teamQuery.data?.license_managers.length ?? 0} active · {teamQuery.data?.pending_invitations.length ?? 0} invitation pending</span></div>
      <div className="hidden grid-cols-[minmax(0,1.2fr)_minmax(150px,.6fr)_minmax(130px,.5fr)_150px] gap-4 bg-surface-raised px-3 py-2.5 text-xs font-bold text-muted md:grid"><span>Name</span><span>Role</span><span>Status</span><span>Actions</span></div>
      {people.filter((person) => person.kind !== 'owner').map((person) => <article className="grid gap-3 border-b border-border px-3 py-5 last:border-b-0 md:grid-cols-[minmax(0,1.2fr)_minmax(150px,.6fr)_minmax(130px,.5fr)_150px] md:items-center" key={person.rowId}><Person name={person.name} email={person.email} /><div><span className="mb-1 block text-xs font-bold text-muted md:hidden">Role</span><span className="text-sm">{person.role}</span></div><div><span className="mb-1 block text-xs font-bold text-muted md:hidden">Status</span><span className={`w-fit rounded-full px-3 py-1.5 text-xs font-bold ${person.status === 'Active' ? 'bg-success-soft text-success' : 'bg-warning-soft text-warning'}`}>{person.status}</span></div>{person.kind === 'invitation' ? <div><span className="mb-1 block text-xs font-bold text-muted md:hidden">Actions</span><div className="flex flex-wrap gap-3"><button className="border-0 bg-transparent text-sm font-bold text-brand disabled:opacity-55" type="button" disabled={!canInvite || resendMutation.isPending || revokeMutation.isPending} onClick={() => resendMutation.mutate(person.invitationId)}>Resend</button><button className="border-0 bg-transparent text-sm font-bold text-danger disabled:opacity-55" type="button" disabled={!canRevoke || resendMutation.isPending || revokeMutation.isPending} onClick={() => { if (window.confirm(`Revoke the invitation for ${person.email}?`)) revokeMutation.mutate(person.invitationId) }}>Revoke</button></div></div> : <div><span className="mb-1 block text-xs font-bold text-muted md:hidden">Actions</span>{canTransfer ? <button className="inline-flex min-h-9 items-center gap-1.5 border-0 bg-transparent p-0 text-sm font-bold text-brand disabled:opacity-55" type="button" disabled={transferMutation.isPending} onClick={() => { if (window.confirm(`Make ${person.name} the Organization Owner? You will become a License Manager.`)) transferMutation.mutate(person.membership_id) }}><Crown size={16} />Make owner</button> : <span className="text-sm text-muted">Active</span>}</div>}</article>)}
      {people.every((person) => person.kind === 'owner') ? <div className="py-8 text-center"><strong className="block text-sm">No License Managers yet</strong><p className="mt-1 text-xs text-muted">Invite a License Manager to help manage organization licenses.</p></div> : null}
    </section>
    <p className="flex items-start gap-3 rounded-control bg-surface-muted px-4 py-3 text-sm text-muted"><ShieldCheck className="mt-0.5 shrink-0" size={19} />Only the Organization Owner can transfer organization ownership. Digital PTT support can help when the owner is unavailable.</p>
    </> : null}
  </div>
}

function TeamState({ icon, title, text, action }: { icon: ReactNode; title: string; text: string; action?: ReactNode }) {
  return <section className="flex items-start gap-3 rounded-panel border border-border bg-white px-5 py-4"><span className="mt-0.5 shrink-0">{icon}</span><div><h3 className="text-base">{title}</h3><p className="mt-1 text-sm text-muted">{text}</p>{action ? <div className="mt-3">{action}</div> : null}</div></section>
}

function messageFrom(error: unknown) {
  return error instanceof Error ? error.message : 'Could not update the organization team.'
}

function Person({ name, email }: { name: string; email: string }) {
  const initials = name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase()
  return <div className="flex min-w-0 items-center gap-3"><span className="inline-flex size-11 shrink-0 items-center justify-center rounded-full bg-brand-soft text-sm font-bold text-brand">{initials}</span><div className="min-w-0"><strong className="block truncate">{name}</strong><span className="block truncate text-sm text-muted">{email}</span></div></div>
}
