# Generated by Django 6.0.6 on 2026-08-18 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_bulk_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='license_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='license_term_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='licensing_role',
            field=models.CharField(choices=[('standard', 'Standard product'), ('licensed_product', 'Licensed product'), ('license_product', 'License product')], db_index=True, default='standard', max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='required_license_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compatible_products', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['licensing_role', 'status', 'is_active'], name='products_pr_licensi_467295_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('license_capacity__isnull', True), ('license_term_days__isnull', True), ('licensing_role', 'standard'), ('required_license_product__isnull', True)), models.Q(('license_capacity__isnull', True), ('license_term_days__isnull', True), ('licensing_role', 'licensed_product'), ('required_license_product__isnull', False)), models.Q(('license_capacity__isnull', False), ('license_term_days__isnull', False), ('licensing_role', 'license_product'), ('required_license_product__isnull', True)), _connector='OR'), name='products_licensing_metadata_by_role'),
        ),
    ]
