# Generated by Django 6.0.8 on 2026-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_inventoryadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_layout',
            field=models.CharField(choices=[('radio', 'Radio'), ('license', 'License'), ('accessory', 'Accessory')], default='accessory', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='presentation_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='show_in_highlights',
            field=models.BooleanField(default=False),
        ),
    ]
