# Generated by Django 6.0.8 on 2026-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_initialize_product_presentation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='products_licensing_metadata_by_role',
        ),
        migrations.AddField(
            model_name='product',
            name='license_billing_model',
            field=models.CharField(blank=True, choices=[('capacity', 'Legacy capacity'), ('per_radio', 'Per radio')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('license_billing_model__isnull', True), ('license_capacity__isnull', True), ('license_term_days__isnull', True), ('licensing_role', 'standard'), ('required_license_product__isnull', True)), models.Q(('license_billing_model__isnull', True), ('license_capacity__isnull', True), ('license_term_days__isnull', True), ('licensing_role', 'licensed_product'), ('required_license_product__isnull', False)), models.Q(('license_capacity__isnull', False), ('license_term_days__isnull', False), ('licensing_role', 'license_product'), ('required_license_product__isnull', True), models.Q(('license_billing_model__isnull', True), ('license_billing_model', 'capacity'), _connector='OR')), models.Q(('license_billing_model', 'per_radio'), ('license_term_days__isnull', False), ('licensing_role', 'license_product'), ('required_license_product__isnull', True)), _connector='OR'), name='products_licensing_metadata_by_role'),
        ),
    ]
