# Generated by Django 6.0.6 on 2026-08-18 06:50

import django.db.models.deletion
import django.utils.timezone
import licensing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
        ('orders', '0007_alter_order_status'),
        ('products', '0007_product_license_capacity_product_license_term_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_number', models.CharField(default=licensing.models.generate_license_number, editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('active', 'Active'), ('expiring_soon', 'Expiring soon'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=24)),
                ('capacity', models.PositiveIntegerField()),
                ('used_capacity', models.PositiveIntegerField(default=0)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, db_index=True, null=True)),
                ('renews_on', models.DateField(blank=True, null=True)),
                ('license_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_licenses', to='products.product')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licensing.organization')),
                ('source_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_licenses', to='orders.orderitem')),
            ],
            options={
                'ordering': ('expires_on', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LicenseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('provisioned', 'License provisioned'), ('renewed', 'License renewed'), ('expired', 'License expired'), ('notification_sent', 'Notification sent'), ('invitation_sent', 'Invitation sent'), ('invitation_accepted', 'Invitation accepted'), ('invitation_revoked', 'Invitation revoked'), ('adjusted', 'Manual adjustment'), ('allocated', 'Product capacity allocated'), ('allocation_released', 'Product allocation released')], db_index=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_events_performed', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_events', to='licensing.organizationinvitation')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='licensing.license')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_events', to='licensing.organization')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProductLicenseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released')], db_index=True, default='active', max_length=16)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='licensing.license')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_allocations', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_allocations', to='products.product')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['organization', 'status'], name='licensing_l_organiz_945a93_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['organization', 'license_product', 'status'], name='licensing_l_organiz_1c4e9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='licensing_license_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(condition=models.Q(('used_capacity__gte', 0), ('used_capacity__lte', models.F('capacity'))), name='licensing_license_used_within_capacity'),
        ),
        migrations.AddIndex(
            model_name='licenseevent',
            index=models.Index(fields=['organization', 'event_type', 'occurred_at'], name='licensing_l_organiz_6318c9_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseevent',
            index=models.Index(fields=['license', 'occurred_at'], name='licensing_l_license_d8d5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='productlicenseallocation',
            index=models.Index(fields=['license', 'status'], name='licensing_p_license_adfa9b_idx'),
        ),
        migrations.AddIndex(
            model_name='productlicenseallocation',
            index=models.Index(fields=['order_item', 'status'], name='licensing_p_order_i_2f862d_idx'),
        ),
        migrations.AddConstraint(
            model_name='productlicenseallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='licensing_allocation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='productlicenseallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('released_at__isnull', True), ('status', 'active')), models.Q(('released_at__isnull', False), ('status', 'released')), _connector='OR'), name='licensing_allocation_release_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='productlicenseallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('license', 'order_item'), name='licensing_one_active_allocation_per_license_order_item'),
        ),
    ]
