# Generated by Django 6.0.6 on 2026-08-18 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_license_licenseevent_productlicenseallocation_and_more'),
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseOrderItemProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('license_purchase', 'License purchase'), ('product_allocation', 'Product allocation')], max_length=24)),
                ('created_license_ids', models.JSONField(blank=True, default=list)),
                ('renewed_license_ids', models.JSONField(blank=True, default=list)),
                ('allocation_ids', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='license_provisioning_record', to='orders.orderitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_provisioning_records', to='licensing.organization')),
            ],
            options={
                'ordering': ('completed_at', 'id'),
                'indexes': [models.Index(fields=['organization', 'operation', 'completed_at'], name='licensing_l_organiz_cb75b9_idx')],
            },
        ),
    ]
