# Generated by Django 6.0.8 on 2026-09-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_organization_status_and_owner_invitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseevent',
            name='event_type',
            field=models.CharField(choices=[('provisioned', 'License provisioned'), ('renewed', 'License renewed'), ('expired', 'License expired'), ('cancelled', 'License cancelled'), ('notification_sent', 'Notification sent'), ('invitation_sent', 'Invitation sent'), ('invitation_accepted', 'Invitation accepted'), ('invitation_revoked', 'Invitation revoked'), ('ownership_transferred', 'Organization ownership transferred'), ('adjusted', 'Manual adjustment'), ('allocated', 'Product capacity allocated'), ('allocation_released', 'Product allocation released')], db_index=True, max_length=32),
        ),
    ]
