# Generated by Django 6.0.8 on 2026-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0006_alter_licenseevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='billing_model',
            field=models.CharField(choices=[('legacy_capacity', 'Legacy capacity'), ('per_radio_order', 'Per-radio order')], db_index=True, default='legacy_capacity', max_length=24),
        ),
    ]
