# Generated by Django 6.0.6 on 2026-06-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('requester_company_name', models.CharField(blank=True, max_length=255)),
                ('requester_contact_person', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(db_index=True, max_length=254)),
                ('requester_phone', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('specifications', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Quote Request Item',
                'verbose_name_plural': 'Quote Request Items',
                'ordering': ('id',),
            },
        ),
    ]
