# Generated by Django 6.0.6 on 2026-08-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quoterequest_admin_message_quoterequest_quoted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('approved', 'Accepted'), ('closed', 'Closed')], db_index=True, default='new', max_length=20),
        ),
    ]
