# Generated by Django 6.0.6 on 2026-08-11 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def reopen_unconverted_quotes(apps, schema_editor):
    QuoteRequest = apps.get_model("quotes", "QuoteRequest")
    QuoteRequest.objects.filter(status="quoted", orders__isnull=True).update(status="reviewing")


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_quoterequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='admin_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='customer_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='invoice_pdf',
            field=models.FileField(blank=True, upload_to='quotes/invoices/'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('quoted', 'Invoice sent'), ('approved', 'Converted'), ('closed', 'Closed')], db_index=True, default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='QuoteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], max_length=20)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_messages', to=settings.AUTH_USER_MODEL)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='quotes.quoterequest')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['quote_request', 'created_at'], name='quotes_quot_quote_r_8d17f5_idx')],
            },
        ),
        migrations.RunPython(reopen_unconverted_quotes, migrations.RunPython.noop),
    ]
