# Generated by Django 6.0.8 on 2026-08-31 03:04

import common.storage
from pathlib import Path
import shutil

from django.conf import settings
from django.db import migrations, models


def move_existing_invoices_to_private_storage(apps, schema_editor):
    QuoteRequest = apps.get_model("quotes", "QuoteRequest")
    public_root = Path(settings.MEDIA_ROOT).resolve()
    private_root = Path(settings.PRIVATE_MEDIA_ROOT).resolve()
    if public_root == private_root:
        return

    for stored_name in QuoteRequest.objects.exclude(invoice_pdf="").values_list("invoice_pdf", flat=True):
        source = (public_root / stored_name).resolve()
        destination = (private_root / stored_name).resolve()
        if not source.is_relative_to(public_root) or not destination.is_relative_to(private_root):
            continue
        if not source.is_file():
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        if destination.exists():
            source.unlink()
        else:
            shutil.move(str(source), str(destination))


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_distinguish_cancelled_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='invoice_pdf',
            field=models.FileField(blank=True, storage=common.storage.PrivateMediaStorage(), upload_to='quotes/invoices/'),
        ),
        migrations.RunPython(move_existing_invoices_to_private_storage, migrations.RunPython.noop),
    ]
