# Generated by Django 6.0.8 on 2026-09-03 02:10

from django.db import migrations, models


def migrate_quote_payment_statuses(apps, schema_editor):
    QuoteRequest = apps.get_model('quotes', 'QuoteRequest')
    QuoteRequest.objects.filter(status='quoted').update(status='awaiting_payment')
    QuoteRequest.objects.filter(status='approved').update(status='payment_confirmed')


def restore_legacy_quote_statuses(apps, schema_editor):
    QuoteRequest = apps.get_model('quotes', 'QuoteRequest')
    QuoteRequest.objects.filter(status='quote_approved').update(status='reviewing')
    QuoteRequest.objects.filter(
        status__in=['invoice_sent', 'awaiting_payment', 'payment_rejected'],
    ).update(status='quoted')
    QuoteRequest.objects.filter(status='payment_confirmed').update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_alter_quoterequest_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='payment_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(
            migrate_quote_payment_statuses,
            restore_legacy_quote_statuses,
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('quote_approved', 'Quote approved'), ('invoice_sent', 'Invoice sent'), ('awaiting_payment', 'Awaiting payment'), ('payment_confirmed', 'Payment confirmed'), ('payment_rejected', 'Payment rejected'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20),
        ),
    ]
