# Generated by Django 6.0.8 on 2026-08-26 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentattempt_renewal_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(blank=True, max_length=32)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_events', to='payments.paymentattempt')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.paymentprovider')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['provider', 'status', 'created_at'], name='payments_pa_provide_27bcda_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='payments_provider_event_unique_provider_event')],
            },
        ),
    ]
