# Generated by Django 6.0.8 on 2026-08-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_provider_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='is_customer_available',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
