# Generated by Django 6.0.8 on 2026-08-31 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_organization_status_and_owner_invitations'),
        ('orders', '0012_orderitem_backordered_quantity_and_more'),
        ('payments', '0007_paymentprovider_is_customer_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'succeeded'), models.Q(('external_reference', ''), _negated=True)), fields=('provider', 'external_reference'), name='payments_unique_confirmed_external_reference'),
        ),
    ]
