# Generated by Django 6.0.8 on 2026-09-03 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentattempt_payments_unique_confirmed_external_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('attempt_created', 'Attempt created'), ('manual_confirmation', 'Manual confirmation'), ('manual_rejection', 'Manual rejection'), ('refund', 'Refund'), ('status_change', 'Status change')], max_length=32)),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], max_length=20)),
                ('invoice_reference', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_status_events', to=settings.AUTH_USER_MODEL)),
                ('payment_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='payments.paymentattempt')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['payment_attempt', 'created_at'], name='payments_pa_payment_676149_idx'), models.Index(fields=['event_type', 'created_at'], name='payments_pa_event_t_4d6046_idx')],
            },
        ),
    ]
