from django.urls import path

from licensing.admin_views import (
    AdminOrganizationLicenseAdjustmentView,
    AdminOrganizationLicenseDetailView,
    AdminOrganizationLicenseHistoryView,
    AdminOrganizationLicenseListView,
    AdminOrganizationLicenseNotificationView,
    AdminOrganizationRenewalInvoiceView,
    AdminOrganizationUsersView,
    AdminOrganizationInvitationCreateView,
    AdminOrganizationInvitationResendView,
    AdminOrganizationInvitationRevokeView,
    AdminOrganizationOwnershipTransferView,
)


urlpatterns = [
    path(
        "organizations/",
        AdminOrganizationLicenseListView.as_view(),
        name="admin-licensing-organization-list",
    ),
    path(
        "organizations/<int:organization_id>/",
        AdminOrganizationLicenseDetailView.as_view(),
        name="admin-licensing-organization-detail",
    ),
    path(
        "organizations/<int:organization_id>/history/",
        AdminOrganizationLicenseHistoryView.as_view(),
        name="admin-licensing-organization-history",
    ),
    path(
        "organizations/<int:organization_id>/notifications/",
        AdminOrganizationLicenseNotificationView.as_view(),
        name="admin-licensing-organization-notifications",
    ),
    path(
        "organizations/<int:organization_id>/renewal-invoice/",
        AdminOrganizationRenewalInvoiceView.as_view(),
        name="admin-licensing-organization-renewal-invoice",
    ),
    path(
        "organizations/<int:organization_id>/users/",
        AdminOrganizationUsersView.as_view(),
        name="admin-licensing-organization-users",
    ),
    path(
        "organizations/<int:organization_id>/users/invitations/",
        AdminOrganizationInvitationCreateView.as_view(),
        name="admin-licensing-organization-invitation-create",
    ),
    path(
        "organizations/<int:organization_id>/users/ownership-transfer/",
        AdminOrganizationOwnershipTransferView.as_view(),
        name="admin-licensing-organization-ownership-transfer",
    ),
    path(
        "organizations/<int:organization_id>/users/invitations/"
        "<int:invitation_id>/resend/",
        AdminOrganizationInvitationResendView.as_view(),
        name="admin-licensing-organization-invitation-resend",
    ),
    path(
        "organizations/<int:organization_id>/users/invitations/"
        "<int:invitation_id>/revoke/",
        AdminOrganizationInvitationRevokeView.as_view(),
        name="admin-licensing-organization-invitation-revoke",
    ),
    path(
        "organizations/<int:organization_id>/licenses/"
        "<str:license_number>/adjust/",
        AdminOrganizationLicenseAdjustmentView.as_view(),
        name="admin-licensing-organization-license-adjust",
    ),
]
