from django.urls import path

from licensing.views import (
    CartCapacityView,
    ClientLicenseDetailView,
    LicenseAdjustmentView,
    LicenseRenewalOrderView,
    OrganizationInvitationAcceptView,
    OrganizationInvitationCreateView,
    OrganizationInvitationResendView,
    OrganizationInvitationRevokeView,
    OrganizationLicenseListView,
    OrganizationOwnershipTransferView,
    OrganizationSummaryView,
    OrganizationTeamView,
    OrganizationWorkspaceListView,
)


urlpatterns = [
    path("cart-capacity/", CartCapacityView.as_view(), name="licensing-cart-capacity"),
    path(
        "organization/summary/",
        OrganizationSummaryView.as_view(),
        name="licensing-organization-summary",
    ),
    path(
        "organizations/",
        OrganizationWorkspaceListView.as_view(),
        name="licensing-organization-workspace-list",
    ),
    path(
        "organization/licenses/",
        OrganizationLicenseListView.as_view(),
        name="licensing-organization-license-list",
    ),
    path(
        "organization/team/",
        OrganizationTeamView.as_view(),
        name="licensing-organization-team",
    ),
    path(
        "organization/ownership-transfer/",
        OrganizationOwnershipTransferView.as_view(),
        name="licensing-organization-ownership-transfer",
    ),
    path(
        "organization/invitations/",
        OrganizationInvitationCreateView.as_view(),
        name="licensing-organization-invitation-create",
    ),
    path(
        "organization/invitations/accept/",
        OrganizationInvitationAcceptView.as_view(),
        name="licensing-organization-invitation-accept",
    ),
    path(
        "organization/invitations/<int:pk>/resend/",
        OrganizationInvitationResendView.as_view(),
        name="licensing-organization-invitation-resend",
    ),
    path(
        "organization/invitations/<int:pk>/revoke/",
        OrganizationInvitationRevokeView.as_view(),
        name="licensing-organization-invitation-revoke",
    ),
    path(
        "licenses/<str:license_number>/",
        ClientLicenseDetailView.as_view(),
        name="licensing-license-detail",
    ),
    path(
        "licenses/<str:license_number>/renew/",
        LicenseRenewalOrderView.as_view(),
        name="licensing-license-renewal-order",
    ),
    path(
        "licenses/<int:pk>/adjust/",
        LicenseAdjustmentView.as_view(),
        name="licensing-license-adjust",
    ),
]
