# Generated by Django 6.0.8 on 2026-08-31 03:04

from django.db import migrations, models
from django.utils import timezone


def verify_existing_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(email_verified_at__isnull=True).update(email_verified_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(verify_existing_users, migrations.RunPython.noop),
    ]
