# Generated by Django 6.0.6 on 2026-06-22 01:46

from django.db import migrations, models


def seed_site_content(apps, schema_editor):
    SiteSetting = apps.get_model('core', 'SiteSetting')
    settings = SiteSetting.objects.order_by('pk').first()
    if not settings:
        return

    settings.working_hours = 'Monday - Friday, 9:00 AM - 6:00 PM'
    settings.free_shipping_minimum = 500
    settings.about_story = (
        'Founded in 2015, Rack & Bracket began with a simple mission: make enterprise-grade '
        'server infrastructure accessible to businesses of all sizes. What started as a small '
        'operation has grown into a global supplier of server racks and data center solutions.\n\n'
        'We partner with leading manufacturers so every product meets high standards of quality, '
        'reliability, and performance.'
    )
    settings.about_mission = (
        'To provide reliable, affordable infrastructure solutions that empower businesses to '
        'scale with confidence and efficiency.'
    )
    settings.about_vision = (
        'To be the global standard for server rack quality and innovation, shaping the future of '
        'data center infrastructure worldwide.'
    )
    settings.about_team = [
        {'name': 'Alex Mercer', 'role': 'CEO'},
        {'name': 'Sarah Chen', 'role': 'CTO'},
        {'name': 'Marcus Rivera', 'role': 'Head of Operations'},
        {'name': 'Lisa Patel', 'role': 'Customer Success Director'},
    ]
    settings.about_values = [
        {'title': 'Quality', 'desc': 'Products selected for durability, safety, and performance.'},
        {'title': 'Innovation', 'desc': 'Solutions that evolve with modern infrastructure needs.'},
        {'title': 'Support', 'desc': 'Helpful guidance from selection through installation.'},
        {'title': 'Integrity', 'desc': 'Honest pricing and transparent communication.'},
    ]
    settings.about_stats = [
        {'label': 'Customers Served', 'value': 2000, 'suffix': '+'},
        {'label': 'Products Delivered', 'value': 5000, 'suffix': '+'},
        {'label': 'Uptime', 'value': 99.9, 'suffix': '%'},
        {'label': 'Countries', 'value': 50, 'suffix': '+'},
    ]
    settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_stats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_story',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_team',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_values',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_vision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='free_shipping_minimum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='core_contac_is_read_f17b60_idx')],
            },
        ),
        migrations.RunPython(seed_site_content, migrations.RunPython.noop),
    ]
