# Generated by Django 6.0.6 on 2026-06-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting_about_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
