# Generated by Django 6.0.6 on 2026-08-04 01:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesetting_commerce_defaults_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_comparison_eyebrow',
            field=models.CharField(default='CHOOSE WITH CONFIDENCE', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_comparison_products',
            field=models.JSONField(blank=True, default=core.models.default_homepage_comparison_products),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_comparison_title',
            field=models.CharField(default='The right radio for every role', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_contact_cta_label',
            field=models.CharField(default='Contact a specialist', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_contact_cta_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_contact_description',
            field=models.TextField(default='From a single radio to a connected fleet, get practical guidance before you buy.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_contact_eyebrow',
            field=models.CharField(default='NOT SURE WHERE TO START?', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_contact_title',
            field=models.CharField(default="Tell us how your team works. We'll match the right system.", max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_hero_secondary_cta_label',
            field=models.CharField(default='Talk to an expert', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_hero_secondary_cta_url',
            field=models.CharField(default='#contact', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_hero_stats',
            field=models.JSONField(blank=True, default=core.models.default_homepage_hero_stats),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_resources',
            field=models.JSONField(blank=True, default=core.models.default_homepage_resources),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_resources_eyebrow',
            field=models.CharField(default='KNOWLEDGE BASE', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_resources_title',
            field=models.CharField(default='Better communication starts here', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_solution_benefits',
            field=models.JSONField(blank=True, default=core.models.default_homepage_solution_benefits),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_solution_description',
            field=models.TextField(default="GPS-enabled Android radios let authorized users see one another's live locations directly on their devices. Crews can talk, check positions and coordinate across 4G LTE without returning to dispatch."),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_solution_eyebrow',
            field=models.CharField(default='ANDROID GPS FLEET VISIBILITY', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_solution_title',
            field=models.CharField(default='Push-to-talk with live team location', max_length=255),
        ),
    ]
