# Generated by Django 6.0.6 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0014_rename_adminnotification_usernotification")]

    operations = [
        migrations.AlterField(
            model_name="notificationjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("quote_customer_email", "Quote customer email"),
                    ("quote_staff_email", "Quote staff email"),
                    ("quote_webhook", "Quote Power Automate webhook"),
                    ("quote_ready_email", "Quote ready email"),
                    ("quote_message_email", "Quote message email"),
                    ("order_status_email", "Order status email"),
                    ("order_status_webhook", "Order status webhook"),
                    ("license_expiry_email", "License expiry email"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
