# Generated by Django 6.0.8 on 2026-08-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_operational_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bank_beneficiary_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bank_payment_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bank_swift_bic',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bank_transfer_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
