# Generated by Django 6.0.8 on 2026-09-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_request_throttle_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationjob',
            name='kind',
            field=models.CharField(choices=[('quote_customer_email', 'Quote customer email'), ('quote_staff_email', 'Quote staff email'), ('quote_webhook', 'Quote Power Automate webhook'), ('quote_ready_email', 'Quote ready email'), ('quote_message_email', 'Quote message email'), ('order_status_email', 'Order status email'), ('order_status_webhook', 'Order status webhook'), ('order_shipped_email', 'Order shipped email'), ('license_expiry_email', 'License expiry email')], db_index=True, max_length=40),
        ),
    ]
