# Generated by Django 6.0.8 on 2026-09-15 06:40

import products.presentation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_notificationjob_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='product_presentation_defaults',
            field=models.JSONField(default=products.presentation.default_product_presentation),
        ),
    ]
