import type { Category, Product } from '../types'

const pocCategory: Category = {
  id: 1,
  name: 'POC Radios',
  slug: 'poc-radios',
  description: 'Nationwide push-to-talk radios for connected teams.',
  image_url: '',
  is_active: true,
  product_count: 4,
}

const holsterCategory: Category = {
  id: 2,
  name: 'Radio Holsters',
  slug: 'radio-holsters',
  description: 'Field-ready carry systems for radios and accessories.',
  image_url: '',
  is_active: true,
  product_count: 3,
}

const now = new Date().toISOString()

export const fallbackProducts: Product[] = [
  {
    id: 510,
    name: 'IPTT510 - POC handheld radio',
    slug: 'iptt510',
    sku: 'IPTT510',
    brand: 'Digital PTT',
    short_description: 'Compact 4G LTE push-to-talk radio for dependable team communication.',
    description: 'One-touch nationwide communication with dual SIM support and web dispatch.',
    price: '120.00',
    sale_price: null,
    current_price: '120.00',
    bulk_minimum_quantity: null,
    bulk_unit_price: null,
    inventory_quantity: 18,
    licensing_role: 'standard',
    required_license_product: null,
    license_capacity: null,
    license_term_days: null,
    is_stock_tracked: true,
    status: 'published',
    is_featured: true,
    is_active: true,
    category: pocCategory,
    images: [{ image_url: '/images/radio-510.png', alt_text: 'IPTT510 radio', is_primary: true, sort_order: 0 }],
    specifications: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: 810,
    name: 'IPTT810 / IPTT820',
    slug: 'iptt810-iptt820',
    sku: 'IPTT810',
    brand: 'Digital PTT',
    short_description: 'Android handheld POC radio for advanced field workflows.',
    description: 'Connected voice and Android applications in one rugged device.',
    price: '430.00',
    sale_price: null,
    current_price: '430.00',
    bulk_minimum_quantity: null,
    bulk_unit_price: null,
    inventory_quantity: 12,
    licensing_role: 'standard',
    required_license_product: null,
    license_capacity: null,
    license_term_days: null,
    is_stock_tracked: true,
    status: 'published',
    is_featured: true,
    is_active: true,
    category: pocCategory,
    images: [{ image_url: '/images/radio-810.png', alt_text: 'IPTT810 radio', is_primary: true, sort_order: 0 }],
    specifications: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: 81,
    name: 'IPTT81 Dual Mode',
    slug: 'iptt81-dual-mode',
    sku: 'IPTT81',
    brand: 'Digital PTT',
    short_description: 'POC and analog dual-mode communications.',
    description: 'Bridge cellular and conventional radio teams with one handheld.',
    price: '340.00',
    sale_price: null,
    current_price: '340.00',
    bulk_minimum_quantity: null,
    bulk_unit_price: null,
    inventory_quantity: 4,
    licensing_role: 'standard',
    required_license_product: null,
    license_capacity: null,
    license_term_days: null,
    is_stock_tracked: true,
    status: 'published',
    is_featured: true,
    is_active: true,
    category: pocCategory,
    images: [{ image_url: '/images/radio-t81.png', alt_text: 'IPTT81 radio', is_primary: true, sort_order: 0 }],
    specifications: [],
    created_at: now,
    updated_at: now,
  },
  ...[
    ['Field Harness Carry System', 'field-harness-carry-system', 'HOLS001', '18.00'],
    ['Lightweight Chest Pack', 'lightweight-chest-pack', 'HOLS002', '15.00'],
    ['Universal Shoulder Holster', 'universal-shoulder-holster', 'HOLS003', '12.00'],
  ].map(([name, slug, sku, price], index): Product => ({
    id: 900 + index,
    name,
    slug,
    sku,
    brand: 'Digital PTT',
    short_description: 'Secure hands-free carry for professional radios.',
    description: 'Adjustable field-ready radio carry system with reinforced webbing.',
    price,
    sale_price: null,
    current_price: price,
    bulk_minimum_quantity: null,
    bulk_unit_price: null,
    inventory_quantity: 20 - index * 3,
    licensing_role: 'standard',
    required_license_product: null,
    license_capacity: null,
    license_term_days: null,
    is_stock_tracked: true,
    status: 'published',
    is_featured: false,
    is_active: true,
    category: holsterCategory,
    images: [{ image_url: '/images/holsters-hero.png', alt_text: name, is_primary: true, sort_order: 0 }],
    specifications: [],
    created_at: now,
    updated_at: now,
  })),
]

export const fallbackCategories = [pocCategory, holsterCategory]
